INSERT INTO SPRINGBOOT_DATA.EMPLOYEE(ID, DEPT_NAME, DOB, EMAIL, NAME,TITLE)
VALUES(1, 'CP','1/1/2020' ,'shawn@yahoo.com' , 'shawn',  'NA' );
INSERT INTO SPRINGBOOT_DATA.EMPLOYEE(ID, DEPT_NAME, DOB, EMAIL, NAME,TITLE)
VALUES(2, 'NA','1/1/2020' ,'shawn@yaoo.com' , 'ron',  'CP' );
INSERT INTO SPRINGBOOT_DATA.EMPLOYEE(ID, DEPT_NAME, DOB, EMAIL, NAME,TITLE)
VALUES(3, 'ER','1/1/2020' ,'shawn@ahoo.com' , 'jon',  'EP' );
INSERT INTO SPRINGBOOT_DATA.EMPLOYEE(ID, DEPT_NAME, DOB, EMAIL, NAME,TITLE)
VALUES(4, 'IT','1/1/2020' ,'shan@yahoo.com' , 'tom',  'vp' );