--CREATE SCHEMA SPRINGBOOT_DATA;

--DROP TABLE IF EXISTS SPRINGBOOT_DATA.EMPLOYEE;
DROP TABLE IF EXISTS SPRINGBOOT_DATA.EMPLOYEE;

CREATE TABLE SPRINGBOOT_DATA.EMPLOYEE(
ID INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
DOB VARCHAR(255) NOT NULL,
TITLE VARCHAR(255) NOT NULL,
DEPT_NAME VARCHAR(20) NOT NULL
)