INSERT INTO PERSON VALUES (1,'SHAWN', 'DALLAS','TX');
INSERT INTO PERSON VALUES (2,'JOBIN', 'AUSTIN','KS');
INSERT INTO PERSON VALUES (3,'AFIF', 'SEATTLE','CA');
INSERT INTO PERSON VALUES (4,'ROBERT', 'CHICAGO','IL');